name: cristobalarias.com
favicon: null
layout_spectrum: 0.9522230352740735
typography_spectrum: 0.4762277053669095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.631300900131464
  lightness: 0.2287947277072817
  saturation: 0.2624919777736068
  rhythmicContrast: 0.6078141955658793
purpose: []
